### ISSUE TITLE
Question about getting textured meshes

### ISSUE THREAD

**Issue by TLB-MISS** [fraunhoferhhi/neural-deferred-shading#9]
Hi, @mworchel @GreenFoxLight !!
Thank you for revealing good research. I have one question for you.

Is it possible to get mesh face (vertex if not possible) color from shader?
If there is a possible process, please let me know!

Thanks

**Comment by mworchel** [comment]
Hi @TLB-MISS,

generally, the shader outputs a _view-dependent_ color, so it is difficult to get one representative color per vertex.

You could use the vertex normal as view direction to obtain a "front-facing" color per vertex. For diffuse materials, this should be ok as their appearance is view independent anyway. However, it is not clear if this operation would be meaningful for materials with specular reflection.

Best, Markus

**Comment by TLB-MISS** [comment]
@mworchel 

Thank you for kind reply!
Your answer means that the shader shows the color of the (view-dependent) mesh vertex(not mesh face)?

**Comment by mworchel** [comment]
The shader can output a view-dependent color for _every_ point in 3D space (think of radiance volume like NeRF), because it is queried with a 3D position and a direction. I proposed evaluating it at the vertex positions but of course it can be evaluated on the faces. However, the output will obviously not be constant per face.

Hope this helps.

**Comment by TLB-MISS** [comment]
@mworchel 

It is clear. Thank you!
